version: '3'

services:
  web:
    build:
      context: .
      dockerfile: buildfiles/Dockerfile.web
    image: web:latest
    command: gunicorn server.wsgi:application --bind 0.0.0.0:8000 --reload --timeout 30
    volumes:
      - ./server:/code
      - ./storage:/storage
      - static_volume:/staticfiles
      - media_volume:/mediafiles
      - ./server/core/static/core:/staticfiles/core
    env_file:
      - vars.env
    environment:
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
      - SECRET_KEY=${SECRET_KEY}
    expose:
      - 8000
    depends_on:
      - db
    links:
      - db:db

  db:
    image: postgres:10.5-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=server_db

  nginx:
    build:
      context: buildfiles
      dockerfile: Dockerfile.nginx
    volumes:
      - static_volume:/staticfiles
      - media_volume:/mediafiles
      - ./server/core/static/core:/staticfiles/core
    ports:
      - ${LOCAL_PORT}:80
    depends_on:
      - web
      - flower

  rabbitmq:
    image: rabbitmq:3.7.18-management-alpine
    command: rabbitmq-server -h rabbit
    environment:
      - RABBITMQ_ERLANG_COOKIE=sadovhw734of278r
      - RABBITMQ_DEFAULT_USER=rabbitmq_user
      - RABBITMQ_DEFAULT_PASS=rabbitmq_pass123098
    ports:
      - 5672:5672
      - 15672:15672 # for flower (rabbitmq api)

  celery:
    image: web:latest
    entrypoint: /bin/sh -c "mkdir -p /storage/logs && celery worker --statedb=/storage/state.db -A server -E -l info --logfile=/storage/logs/celery.log"
    volumes:
      - ./server:/code
      - ./storage:/storage
    env_file:
      - vars.env
    environment:
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - web
      - rabbitmq

  flower:
    image: web:latest
    entrypoint: celery flower -A server --port=5555 --url_prefix=flower --persistent=True --db=/storage/flower.db --basic_auth=${FLOWER_USER}:${FLOWER_PASS}
    volumes:
      - ./server:/code
      - ./storage:/storage
    env_file:
      - vars.env
    environment:
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - rabbitmq
      - celery
    ports:
      - 5555:5555

volumes:
  static_volume:
  media_volume:
  postgres_data:
