# Generated by Django 2.1.7 on 2019-03-07 20:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_name', models.CharField(default='', max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('warning', models.CharField(default='', max_length=100)),
                ('error', models.CharField(default='', max_length=1000)),
                ('deleted', models.BooleanField(default=False)),
                ('restarted', models.IntegerField(default=0)),
                ('touched', models.DateTimeField(auto_now=True)),
                ('queue_id', models.IntegerField(null=True)),
                ('ip', models.GenericIPAddressField()),
                ('status', models.CharField(choices=[('L.STR', 'Started on local machine'), ('L.ERR', 'Error on local machine'), ('L.PRE', 'Preparing data on local machine'), ('L.CPY', 'Copying from local to remote machine'), ('R.QUE', 'Job queued on remote machine'), ('R.ERR', 'Error on remote machine'), ('R.RUN', 'Running on remote machine'), ('R.CPY', 'Copying from remote to local machine'), ('L.FIN', 'Finishing on local machine'), ('L.CPL', 'Job completed')], max_length=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
