# pull official base image
FROM python:3.6
MAINTAINER Mikhail Ignatov <mikhail.ignatov@stonybrook.edu>

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

COPY requirements.txt .
RUN pip install -r requirements.txt

# install netcat to run it in entrypoint.sh
RUN apt-get update && apt-get install netcat -y

# set work directory
WORKDIR /code
ENTRYPOINT ["./entrypoint.sh"]
